### ISSUE TITLE
"configOptions" property not work

### ISSUE THREAD

**Issue by benjaminliugang** [PredixDev/px-deck-selector#6]
Checked the source code, it seems we need to set the "configOptions" property's type as Object, then it will works well.

**Comment by runn-vermel** [comment]
Hi @benjaminliugang - i'm going to close this issue. Please use our provided template for submitting issues. also, if/when you reopen this issue please provide some sample code.

**Comment by runn-vermel** [comment]
btw, if you think you have a solution, please feel free submit it as a Pull Request.

**Comment by zwaltz** [comment]
@runn-vermel - I'm going to open a Pull Request for this issue. The configOptions property should just have it's type declared as Object.

**Comment by runn-vermel** [comment]
can you explain what's not working, and how this PR will fix it please?

**Comment by randyaskin** [comment]
The issue was obscured by the fact that we were binding directly to a JavaScript object in our demo page instead of passing it in as a string as you showed in your email. I've fixed it in v1.6.9 and also in our new v2* chain on master (you should use v1.6.9 for now though). Thanks for pointing it out.
